# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SEDucate
                                 A QGIS plugin
 Create Sedimentology Log Excerices
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-11-03
        copyright            : (C) 2021 by Bjorn Nyberg, Sigrid Næsheim, Henk Keers
        email                : bjorn.nyberg@uib.no
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Bjorn Nyberg, Sigrid Næsheim, Henk Keers'
__date__ = '2021-11-03'
__copyright__ = '(C) 2021 by Bjorn Nyberg, Sigrid Næsheim, Henk Keers'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SEDucate class from file SEDucate.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SEDucate import SEDucatePlugin
    return SEDucatePlugin()
